name: Publish website on release

on:
  push:
    tags:
      - rel/avatica-[0-9]+.[0-9]+.[0-9]+ # Trigger only when the tag matches rel/avatica-X.Y.Z

jobs:
  publish-website:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build site
        working-directory: site
        run: |
          docker-compose run -e JEKYLL_UID=$(id -u) -e JEKYLL_GID=$(id -g) build-site
      - name: Build javadoc
        working-directory: site
        run: |
          docker-compose run generate-javadoc
      - uses: actions/checkout@v3
        with:
          repository: apache/calcite-site
          path: calcite-site
          token: ${{ secrets.CALCITE_WEBSITE_BUILD }}
      - name: Publish site
        working-directory: calcite-site
        run: |
          git config user.email ${{ github.actor }}@users.noreply.github.com
          git config user.name ${{ github.actor }}
          rm -rf avatica/
          mv ../site/target/avatica/ .
          git add .
          if ! git diff-index --quiet HEAD; then
            git commit -m "Website deployed from calcite-avatica@$GITHUB_SHA"
            git push origin master
          fi
